name: Start Workspace On Issue Creation or Comment

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    if: >-
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@coder')) || 
      (github.event_name == 'issues' && contains(github.event.issue.body, '@coder'))
    environment: coder-demo
    timeout-minutes: 5
    steps:
      - name: Start Coder workspace
        uses: coder/start-workspace-action@v0.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-username: >-
            ${{
              (github.event_name == 'issue_comment' && github.event.comment.user.login) || 
              (github.event_name == 'issues' && github.event.issue.user.login)
            }}
          coder-url: ${{ secrets.CODER_URL }}
          coder-token: ${{ secrets.CODER_TOKEN }}
          template-name: ${{ secrets.CODER_TEMPLATE_NAME }}
          parameters: |-
            AI Prompt: |
              Use the gh CLI tool to read the details of issue https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }} and then address it.
              
              Then, submit a pull request. In the PR body, after your description, be sure to link:
                - Your workspace URL in the body (e.g. https://dev.coder.com/@bpmct/brown-alpaca-18)
                - A preview appp URL (e.g. https://codercom-preview--dev--issue-74--bpmct--apps.dev.coder.com/).
                - The issue number you are fixing
                Read the `env` vars in your workspace to get the proper username and workspace name.
              
                When comments occur, first respond and then start working on their feedback. Push your changes.  End with a task stating "PR Submitting, waiting for approval"
